// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ErrorObject error object
// swagger:model ErrorObject
type ErrorObject struct {

	// code
	Code int64 `json:"code,omitempty"`

	// Description of what went wrong (if we can tell)
	Message string `json:"message,omitempty"`
}

// Validate validates this error object
func (m *ErrorObject) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ErrorObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrorObject) UnmarshalBinary(b []byte) error {
	var res ErrorObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
